### ISSUE TITLE
[BE/TEST] 각종 테스트

### ISSUE THREAD

**Issue by LJH098** [JNU-econovation/EATceed-BE#359]
## ⚠️ Issue
- 테스트 커버리지를 높이기 위해 작성하지 않은 통합 테스트를 작성

## ✏️ To Do List
- [x] DeleteMember 통합테스트
- [x] UpdateMember 통합테스트
- [x] SSE Controller 테스트
- [x] UpdateWeight 통합테스트
- [x] GetWeight 통합테스트

### 🏞 ScreenShot
- Add any other context or screenshots about the feature request here.

**Comment by hwangdaesun** [comment]
UpdateWeight, GetWeight 통합테스트도 추가요~
